In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
import tensorflow_hub as hub
import tensorflow_text as text
# import tensorflow as tf
from tqdm import tqdm  # Optional: progress bar
import gdown

KeyboardInterrupt: 

In [ ]:
# https://drive.google.com/file/d/1h6DlFxmt9ztvz6s6O6ycw7-BQzY5nzRR/view?usp=sharing
gdown.download(id='1h6DlFxmt9ztvz6s6O6ycw7-BQzY5nzRR', output='04_encoded_labelled_emails.csv', quiet=False)
# labelled_emails_df = pd.read_csv('../data/04_encoded_labelled_emails.csv')
labelled_emails_df = pd.read_csv('04_encoded_labelled_emails.csv')
labelled_emails_df.head()

Downloading...
From: https://drive.google.com/uc?id=1h6DlFxmt9ztvz6s6O6ycw7-BQzY5nzRR
To: /Users/pkchoy/code/data_science_bootcamp/predictor-with-files/notebooks/04_encoded_labelled_emails.csv
100%|██████████| 5.98M/5.98M [00:00<00:00, 17.3MB/s]


Date                       From  \
0  Fri, 25 Aug 2000 03:30:00 -0700 (PDT)    phillip.allen@enron.com   
1  Mon, 10 Jul 2000 06:54:00 -0700 (PDT)    phillip.allen@enron.com   
2  Tue, 24 Apr 2001 13:05:00 -0700 (PDT)    phillip.allen@enron.com   
3   Mon, 5 Mar 2001 07:21:00 -0800 (PST)    phillip.allen@enron.com   
4  Wed, 13 Dec 2000 06:35:00 -0800 (PST)  critical.notice@enron.com   

                                                  To  \
0                            brad.mcsherry@enron.com   
1                               al.pollard@enron.com   
2                                jsmith@austintx.com   
3                               cbpres@austin.rr.com   
4  ywang@enron.com, patti.sullivan@enron.com, phi...   

                                     Subject                     X_From  \
0                       Cc: [EMAIL], [EMAIL]            Phillip K Allen   
1                         Re: Katy flatlands            Phillip K Allen   
2                              Re: The Stage            Phillip K Allen   
3                       Cc: [EMAIL], [EMAIL]            Phillip K Allen   
4  New Notice from Transwestern Pipeline Co.  critical.notice@Enron.com   

                                                X_To  \
0                                      Brad McSherry   
1                                         Al Pollard   
2                  Jeff Smith  <jsmith@austintx.com>   
3                               cbpres@austin.rr.com   
4  ywang@Enron.com, Patti.Sullivan@Enron.com, Phi...   

                                             Message  \
0  Brad,\nWith regard to Tori Kuykendall, I would...   
1  Al,\nI am not in good enough shape to ride a c...   
2  I just spoke to the insurance company. They ar...   
3  George,\nI am back in the office and ready to ...   
4  Transwestern Pipeline Co. posted new notice(s)...   

                                      Entire-Message DISC_rule DISC_manual  \
0  Cc: [EMAIL], [EMAIL] Brad,\nWith regard to Tor...     ['S']          []   
1  Re: Katy flatlands Al,\nI am not in good enoug...     ['D']          []   
2  Re: The Stage I just spoke to the insurance co...     ['C']          []   
3  Cc: [EMAIL], [EMAIL] George,\nI am back in the...     ['I']          []   
4  New Notice from Transwestern Pipeline Co. Tran...     ['C']          []   

  DISC_final  D  I  S  C  
0      ['S']  0  0  1  0  
1      ['D']  1  0  0  0  
2      ['C']  0  0  0  1  
3      ['I']  0  1  0  0  
4      ['C']  0  0  0  1

In [ ]:
labelled_emails_df.isnull().sum()

Date              0
From              0
To                0
Subject           0
X_From            0
X_To              0
Message           0
Entire-Message    0
DISC_rule         0
DISC_manual       0
DISC_final        0
D                 0
I                 0
S                 0
C                 0
dtype: int64

In [ ]:
mlb = MultiLabelBinarizer(classes=['D', 'I', 'S', 'C'])
Y = mlb.fit_transform(labelled_emails_df['DISC_final']) # Learns the unique labels
mlb.classes_ # The labels learned in sorted order
Y = mlb.transform(labelled_emails_df['DISC_final'])
print(Y)

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 ...
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]]


/Users/pkchoy/code/data_science_bootcamp/predictor-with-files/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ["'", '[', ']'] will be ignored
  warnings.warn(


## Split

In [ ]:
X_train_text, X_test_text, Y_train, Y_test = train_test_split(labelled_emails_df['Entire-Message'], Y, test_size=0.2, random_state=32)
print('Y_train: ', Y_train)
print('Y_test: ', Y_test)
print('shape: ', Y_train.shape, Y_test.shape)

Y_train:  [[0 0 0 1]
 [0 0 0 1]
 [0 1 0 0]
 ...
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]]
Y_test:  [[0 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 ...
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]]
shape:  (1910, 4) (478, 4)


In [ ]:
np.save('../model_data/Y_train.npy', Y_train)
np.save('../model_data/Y_test.npy', Y_test)

## Feature Extraction: Generate BERT Embeddings from Entire-Message of labelled samples

In [ ]:
# bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
# bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3")

# print(os.getcwd())
# print(os.listdir("tfhub_modules"))

bert_preprocess = hub.KerasLayer("../tfhub_modules/bert_preprocess", trainable=False)
bert_encoder = hub.KerasLayer("../tfhub_modules/bert_encoder", trainable=False)

In [ ]:
# def get_bert_embeddings(texts):
#     text_inputs = tf.constant(texts)
#     tokenized_text = bert_preprocess(text_inputs)
#     outputs = bert_encoder(tokenized_text)
#     print(outputs.keys())
#     return outputs['pooled_output'].numpy()

# def get_bert_embeddings(texts, batch_size=96):
#     all_embeddings = []

#     for i in tqdm(range(0, len(texts), batch_size)):
#         batch = texts[i:i + batch_size]
#         batch_inputs = tf.constant(batch)
#         tokenized = bert_preprocess(batch_inputs)
#         outputs = bert_encoder(tokenized)
#         pooled = outputs['pooled_output'].numpy()
#         all_embeddings.append(pooled)

#     return np.vstack(all_embeddings)

# X_train = get_bert_embeddings(X_train_text.tolist())
# X_test = get_bert_embeddings(X_test_text.tolist())

# np.save("../model_data/X_train_bert.npy", X_train)
# np.save("../model_data/X_test_bert.npy", X_test)

# print("X_train", X_train)
# print("X_testX", X_test)

In [ ]:
# all_emails_df = pd.read_csv('../data/04_all_emails_with_labelled_samples.csv')


In [ ]:
# all_emails_df.sample(10, random_state=32)

Date                         From  \
22402  Wed, 15 Mar 2000 09:56:00 -0800 (PST)      michael.burke@enron.com   
21391  Mon, 19 Nov 2001 13:33:56 -0800 (PST)    max.sonnonstine@enron.com   
8258    Tue, 8 May 2001 03:52:00 -0700 (PDT)   jennifer.rudolph@enron.com   
27522  Wed, 19 Dec 2001 14:26:51 -0800 (PST)      lance.jameson@enron.com   
44698  Thu, 10 May 2001 03:57:00 -0700 (PDT)  wade.stubblefield@enron.com   
28785  Wed, 10 Jan 2001 07:49:00 -0800 (PST)           zimin.lu@enron.com   
35942  Mon, 18 Sep 2000 08:25:00 -0700 (PDT)   audrey.robertson@enron.com   
47543   Mon, 5 Nov 2001 11:16:13 -0800 (PST)     josie.jarnagin@enron.com   
6046   Fri, 14 Dec 2001 12:08:03 -0800 (PST)        ruth.jensen@enron.com   
44871  Tue, 26 Jun 2001 11:02:22 -0700 (PDT)          m..presto@enron.com   

                                                      To  \
22402                           stanley.horton@enron.com   
21391                              marie.heard@enron.com   
8258                                   ca.team@enron.com   
27522                               tana.jones@enron.com   
44698  rogers.herndon@enron.com, meredith.eggleston@e...   
28785                         kenneth.parkhill@enron.com   
35942  jeffery.fawcett@enron.com, steven.harris@enron...   
47543                       center.dl-portland@enron.com   
6046   ron.beidelman@enron.com, larry.campbell@enron....   
44871                               greg.wolfe@enron.com   

                                                 Subject  \
22402                         EOTT Sub Unit Options plan   
21391                               Forest and Noble Gas   
8258           NEWS: quick read - calif electric lottery   
27522                                         29th floor   
44698                                      Project Teams   
28785              Storage model change: Commodity Delta   
35942                        Customer Meeting Attendance   
47543  Reminder-Flu Shots-Please respond by 11/6/01 i...   
6046   CAM Applications to Engines with Catalytic Con...   
44871                            Real-time opportunities   

                                                  X_From  \
22402                                      Michael Burke   
21391  Sonnonstine, Max </O=ENRON/OU=NA/CN=RECIPIENTS...   
8258                                    Jennifer Rudolph   
27522  Jameson, Lance </O=ENRON/OU=NA/CN=RECIPIENTS/C...   
44698                                  Wade Stubblefield   
28785                                           Zimin Lu   
35942                                   Audrey Robertson   
47543  Jarnagin, Josie </O=ENRON/OU=NA/CN=RECIPIENTS/...   
6046   Jensen, Ruth </O=ENRON/OU=NA/CN=RECIPIENTS/CN=...   
44871  Presto, Kevin M. </O=ENRON/OU=NA/CN=RECIPIENTS...   

                                                    X_To  \
22402                                     Stanley Horton   
21391  Heard, Marie </O=ENRON/OU=NA/CN=RECIPIENTS/CN=...   
8258                                             CA Team   
27522  Jones, Tana </O=ENRON/OU=NA/CN=RECIPIENTS/CN=T...   
44698  Rogers Herndon, Meredith M Eggleston, Don Blac...   
28785                                   Kenneth Parkhill   
35942  Jeffery Fawcett, Steven Harris, Kevin Hyatt, L...   
47543  DL-Portland World Trade Center </O=ENRON/OU=NA...   
6046   Beidelman, Ron </O=ENRON/OU=NA/CN=RECIPIENTS/C...   
44871  Wolfe, Greg </O=ENRON/OU=NA/CN=RECIPIENTS/CN=G...   

                                                 Message  \
22402  Stan,\nThis my understanding of the proposal\n...   
21391  Marie,\nSince Jay is out this week, I'll be "w...   
8258   * an editorial from today's Wall Street Journa...   
27522  Tana,\nThe suite of offices on 29 will be comp...   
44698  Detailed below are the project teams identifie...   
28785  Dear All,\nI change the storage model output t...   
35942  As of 3:00p today, Monday, September 18, I hav...   
47543  Flu Shot Clinic Sponsored By Enron\nWhen: Tues...   
6046   I

In [ ]:
# X = get_bert_embeddings(all_emails_df['Entire-Message'].tolist())
# no need Y coz that's what we're trying to predict
